export ZSH=$HOME"/.oh-my-zsh"
NVIM_PATH=/usr/local/bin/nvim
export EDITOR=$NVIM_PATH
export SUDO_EDITOR=$NVIM_PATH
export PATH=$PATH:$HOME/.local/bin

ZSH_THEME="agnoster"

plugins=(git vi-mode nvm pyenv)

source $ZSH/oh-my-zsh.sh

alias mutt="neomutt"
alias tmux="tmux -2"

#source ~/dotfiles/zsh/functionsrc
#source ~/dotfiles/zsh/variablesrc
